# Generated by Django 4.1.5 on 2023-10-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=None, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/categories')),
                ('banner', models.ImageField(upload_to='images/categories/banner')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
